name: Runs meilisearch indexing
on:
  workflow_run:
    workflows: ["Runs librestranslate on content change"]
    types:
      - completed
    branches: [dev]

jobs:
  run-search-index-script:
    permissions:
      contents: read
      issues: read
      pull-requests: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo (full history)
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: true
      
      - name: Setup Node server environment
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Run Meilisearch indexing
        run: |
          cd scripts/search-indexer
          npx tsx index.ts
        env:
          MEILI_HOST: ${{ secrets.MEILISEARCH_HOST }}
          MEILI_MASTER_KEY: ${{ secrets.MEILISEARCH_API_KEY }}